### ISSUE TITLE
Error: Cannot find module 'earl-gulp'

### ISSUE THREAD

**Issue by adamellsworth** [breuleux/gulp-earl#1] opened 2015-05-08 14:27 UTC
This error occurs when I try to require `gulp-earl`, `earlify`, or `earl-gulp`.

```
Error: Cannot find module 'earl-gulp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/adamellsworth/projects/.../node_modules/gulp-earl/lib/index.js:3:410)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

---
### devDeps:

```
"earl-gulp": "0.0.1",
"earlify": "0.0.1",
"earlgrey-runtime": "0.0.7",
"gulp-earl": "0.0.1",
```

I've installed `earlgray` globally.

---
### Env.
- node/0.12.2
- iojs/0.12.2
- gulp CLI version 3.8.11

**Comment by breuleux** [comment] 2015-05-08 17:18
Duplicate of this issue, now fixed: https://github.com/breuleux/earl-gulp/issues/1

**Closed as completed by breuleux** 2015-05-08 17:18 UTC
